import type {
  User,
  SystemUser,
  Material,
  ImportHistory,
  Product,
  BOM,
  ProductionOrder,
  StockAlert,
  Activity,
  DashboardStats,
  MonthlyProduction,
  MaterialConsumption,
} from "./types"

// Current user
export const currentUser: User = {
  id: "1",
  name: "Nguyễn Văn Anh",
  email: "admin@craftflow.vn",
  role: "Admin",
}

// Materials data
export const materials: Material[] = [
  {
    id: "1",
    name: "Len cotton cao cấp",
    supplier: "Len Việt Nam",
    category: "Len",
    currentStock: 450,
    minStock: 200,
    unit: "cuộn",
    unitPrice: 45000,
    status: "Good",
    color: "Trắng ngà",
    lastUpdated: "2026-03-18",
  },
  {
    id: "2",
    name: "Len acrylic mềm",
    supplier: "Đông Á Textile",
    category: "Len",
    currentStock: 850,
    minStock: 500,
    unit: "cuộn",
    unitPrice: 28000,
    status: "Good",
    color: "Hồng pastel",
    lastUpdated: "2026-03-17",
  },
  {
    id: "3",
    name: "Len wool Úc",
    supplier: "Import Wool Co.",
    category: "Len",
    currentStock: 120,
    minStock: 100,
    unit: "cuộn",
    unitPrice: 95000,
    status: "Low Stock",
    color: "Nâu đất",
    lastUpdated: "2026-03-19",
  },
  {
    id: "4",
    name: "Mắt thú nhồi bông 8mm",
    supplier: "Phụ kiện Minh Anh",
    category: "Phụ kiện",
    currentStock: 15,
    minStock: 50,
    unit: "hộp",
    unitPrice: 35000,
    status: "Critical",
    lastUpdated: "2026-03-18",
  },
  {
    id: "5",
    name: "Bông gòn nhồi",
    supplier: "Việt Bông",
    category: "Phụ kiện",
    currentStock: 5,
    minStock: 20,
    unit: "gram",
    unitPrice: 150,
    status: "Critical",
    lastUpdated: "2026-03-19",
  },
  {
    id: "6",
    name: "Nút gỗ tròn 15mm",
    supplier: "Phụ kiện Minh Anh",
    category: "Phụ kiện",
    currentStock: 280,
    minStock: 100,
    unit: "cái",
    unitPrice: 2000,
    status: "Good",
    lastUpdated: "2026-03-16",
  },
  {
    id: "7",
    name: "Kim móc len số 3.0",
    supplier: "Dụng cụ Hà Nội",
    category: "Dụng cụ",
    currentStock: 45,
    minStock: 30,
    unit: "cái",
    unitPrice: 25000,
    status: "Good",
    lastUpdated: "2026-03-15",
  },
  {
    id: "8",
    name: "Bộ kim đan tre",
    supplier: "Tre Việt",
    category: "Dụng cụ",
    currentStock: 12,
    minStock: 15,
    unit: "bộ",
    unitPrice: 85000,
    status: "Low Stock",
    lastUpdated: "2026-03-18",
  },
  {
    id: "9",
    name: "Len chunky",
    supplier: "Len Việt Nam",
    category: "Len",
    currentStock: 200,
    minStock: 150,
    unit: "cuộn",
    unitPrice: 55000,
    status: "Good",
    color: "Be",
    lastUpdated: "2026-03-19",
  },
  {
    id: "10",
    name: "Móc khóa kim loại",
    supplier: "Phụ kiện Minh Anh",
    category: "Phụ kiện",
    currentStock: 500,
    minStock: 200,
    unit: "cái",
    unitPrice: 3500,
    status: "Good",
    lastUpdated: "2026-03-17",
  },
]

// Import history
export const importHistory: ImportHistory[] = [
  {
    id: "1",
    materialId: "1",
    materialName: "Len cotton cao cấp",
    quantity: 200,
    unit: "cuộn",
    unitPrice: 45000,
    totalPrice: 9000000,
    supplier: "Len Việt Nam",
    importDate: "2026-03-15",
    note: "Nhập thêm cho đơn hàng lớn",
  },
  {
    id: "2",
    materialId: "2",
    materialName: "Len acrylic mềm",
    quantity: 500,
    unit: "cuộn",
    unitPrice: 28000,
    totalPrice: 14000000,
    supplier: "Đông Á Textile",
    importDate: "2026-03-12",
  },
  {
    id: "3",
    materialId: "4",
    materialName: "Mắt thú nhồi bông 8mm",
    quantity: 10,
    unit: "hộp",
    unitPrice: 35000,
    totalPrice: 350000,
    supplier: "Phụ kiện Minh Anh",
    importDate: "2026-03-10",
  },
]

// Products
export const products: Product[] = [
  {
    id: "1",
    name: "Gấu bông Teddy",
    description: "Gấu bông móc len cao cấp, kích thước 25cm",
    category: "Thú nhồi bông",
    basePrice: 350000,
    suggestedPrice: 420000,
    createdAt: "2026-02-15",
  },
  {
    id: "2",
    name: "Túi đeo chéo handmade",
    description: "Túi đeo chéo móc len, có khóa kéo",
    category: "Túi xách",
    basePrice: 280000,
    suggestedPrice: 350000,
    createdAt: "2026-02-20",
  },
  {
    id: "3",
    name: "Khăn choàng cổ",
    description: "Khăn choàng đan len wool, 180cm x 30cm",
    category: "Phụ kiện thời trang",
    basePrice: 450000,
    suggestedPrice: 550000,
    createdAt: "2026-03-01",
  },
  {
    id: "4",
    name: "Mũ len tai mèo",
    description: "Mũ len đan tay có tai mèo dễ thương",
    category: "Phụ kiện thời trang",
    basePrice: 180000,
    suggestedPrice: 220000,
    createdAt: "2026-03-05",
  },
  {
    id: "5",
    name: "Móc khóa thú mini",
    description: "Móc khóa hình thú nhỏ xinh, nhiều mẫu",
    category: "Móc khóa",
    basePrice: 65000,
    suggestedPrice: 85000,
    createdAt: "2026-03-10",
  },
  {
    id: "6",
    name: "Áo len trẻ em",
    description: "Áo len đan cho bé 1-3 tuổi",
    category: "Quần áo",
    basePrice: 320000,
    suggestedPrice: 400000,
    createdAt: "2026-03-12",
  },
]

// BOMs
export const boms: BOM[] = [
  {
    id: "1",
    productId: "1",
    productName: "Gấu bông Teddy",
    items: [
      { materialId: "1", materialName: "Len cotton cao cấp", quantity: 3, unit: "cuộn" },
      { materialId: "4", materialName: "Mắt thú nhồi bông 8mm", quantity: 2, unit: "cái" },
      { materialId: "5", materialName: "Bông gòn nhồi", quantity: 150, unit: "gram" },
    ],
    totalCost: 157500,
    createdAt: "2026-02-15",
    updatedAt: "2026-03-01",
  },
  {
    id: "2",
    productId: "2",
    productName: "Túi đeo chéo handmade",
    items: [
      { materialId: "2", materialName: "Len acrylic mềm", quantity: 4, unit: "cuộn" },
      { materialId: "10", materialName: "Móc khóa kim loại", quantity: 1, unit: "cái" },
    ],
    totalCost: 115500,
    createdAt: "2026-02-20",
    updatedAt: "2026-02-20",
  },
  {
    id: "3",
    productId: "3",
    productName: "Khăn choàng cổ",
    items: [
      { materialId: "3", materialName: "Len wool Úc", quantity: 5, unit: "cuộn" },
    ],
    totalCost: 475000,
    createdAt: "2026-03-01",
    updatedAt: "2026-03-01",
  },
]

// Production orders
export const productionOrders: ProductionOrder[] = [
  {
    id: "1",
    productId: "1",
    productName: "Gấu bông Teddy",
    quantity: 10,
    status: "Đang sản xuất",
    startDate: "2026-03-15",
    expectedDate: "2026-03-25",
    completedQuantity: 4,
  },
  {
    id: "2",
    productId: "2",
    productName: "Túi đeo chéo handmade",
    quantity: 5,
    status: "Hoàn thành",
    startDate: "2026-03-10",
    expectedDate: "2026-03-18",
    completedDate: "2026-03-17",
    completedQuantity: 5,
  },
  {
    id: "3",
    productId: "5",
    productName: "Móc khóa thú mini",
    quantity: 20,
    status: "Đang sản xuất",
    startDate: "2026-03-18",
    expectedDate: "2026-03-22",
    completedQuantity: 12,
  },
  {
    id: "4",
    productId: "3",
    productName: "Khăn choàng cổ",
    quantity: 3,
    status: "Chờ nguyên liệu",
    startDate: "2026-03-20",
    expectedDate: "2026-03-30",
    completedQuantity: 0,
    note: "Đang chờ len wool Úc",
  },
  {
    id: "5",
    productId: "4",
    productName: "Mũ len tai mèo",
    quantity: 8,
    status: "Đang sản xuất",
    startDate: "2026-03-16",
    expectedDate: "2026-03-24",
    completedQuantity: 3,
  },
]

// Stock alerts
export const stockAlerts: StockAlert[] = [
  {
    id: "1",
    materialId: "4",
    materialName: "Mắt thú nhồi bông 8mm",
    currentStock: 15,
    minStock: 50,
    unit: "hộp",
    status: "Critical",
    createdAt: "2026-03-18",
  },
  {
    id: "2",
    materialId: "5",
    materialName: "Bông gòn nhồi",
    currentStock: 5,
    minStock: 20,
    unit: "gram",
    status: "Critical",
    createdAt: "2026-03-19",
  },
  {
    id: "3",
    materialId: "3",
    materialName: "Len wool Úc",
    currentStock: 120,
    minStock: 100,
    unit: "cuộn",
    status: "Low Stock",
    createdAt: "2026-03-19",
  },
  {
    id: "4",
    materialId: "8",
    materialName: "Bộ kim đan tre",
    currentStock: 12,
    minStock: 15,
    unit: "bộ",
    status: "Low Stock",
    createdAt: "2026-03-18",
  },
]

// Recent activities
export const recentActivities: Activity[] = [
  {
    id: "1",
    type: "production",
    title: "Hoàn thành sản xuất",
    description: "Túi đeo chéo handmade × 5",
    timestamp: "10 phút trước",
  },
  {
    id: "2",
    type: "import",
    title: "Nhập kho",
    description: "Len cotton cao cấp × 200 cuộn",
    timestamp: "2 giờ trước",
  },
  {
    id: "3",
    type: "alert",
    title: "Cảnh báo tồn kho",
    description: "Mắt thú nhồi bông 8mm sắp hết",
    timestamp: "3 giờ trước",
  },
  {
    id: "4",
    type: "product",
    title: "Thêm sản phẩm mới",
    description: "Áo len trẻ em",
    timestamp: "1 ngày trước",
  },
  {
    id: "5",
    type: "production",
    title: "Bắt đầu sản xuất",
    description: "Gấu bông Teddy × 10",
    timestamp: "2 ngày trước",
  },
]

// Dashboard stats
export const dashboardStats: DashboardStats = {
  totalMaterials: 142,
  materialsChange: 12,
  inProduction: 28,
  productionChange: 5,
  completedProducts: 156,
  completedChange: 23,
  stockAlerts: 8,
  alertsChange: -2,
}

// Monthly production data
export const monthlyProduction: MonthlyProduction[] = [
  { month: "T1", produced: 42, target: 12 },
  { month: "T2", produced: 55, target: 18 },
  { month: "T3", produced: 48, target: 15 },
  { month: "T4", produced: 62, target: 20 },
  { month: "T5", produced: 70, target: 22 },
  { month: "T6", produced: 68, target: 18 },
]

// Material consumption data
export const materialConsumption: MaterialConsumption[] = [
  { name: "Len cotton", value: 35, color: "#D4A574" },
  { name: "Len acrylic", value: 25, color: "#4A7C23" },
  { name: "Phụ kiện", value: 15, color: "#5C4D3C" },
  { name: "Len wool", value: 13, color: "#DC3545" },
  { name: "Dụng cụ", value: 12, color: "#8B7355" },
]

// Product categories
export const productCategories = [
  "Thú nhồi bông",
  "Túi xách",
  "Phụ kiện thời trang",
  "Móc khóa",
  "Quần áo",
  "Đồ trang trí",
]

// Material categories
export const materialCategories = ["Len", "Phụ kiện", "Dụng cụ"] as const

// System users
export const systemUsers: SystemUser[] = [
  {
    id: "1",
    name: "Nguyễn Văn Admin",
    email: "admin@craftflow.vn",
    role: "Admin",
    status: "Hoạt động",
    createdAt: "2026-01-15",
  },
  {
    id: "2",
    name: "Trần Thị Kho",
    email: "kho.tran@craftflow.vn",
    role: "Warehouse",
    status: "Hoạt động",
    createdAt: "2026-01-20",
  },
  {
    id: "3",
    name: "Lê Văn Thợ",
    email: "tho.le@craftflow.vn",
    role: "Staff",
    status: "Hoạt động",
    workload: 85,
    createdAt: "2026-02-01",
  },
  {
    id: "4",
    name: "Phạm Thị May",
    email: "may.pham@craftflow.vn",
    role: "Staff",
    status: "Hoạt động",
    workload: 40,
    createdAt: "2026-02-10",
  },
  {
    id: "5",
    name: "Hoàng Văn Cắt",
    email: "cat.hoang@craftflow.vn",
    role: "Staff",
    status: "Vô hiệu hóa",
    workload: 0,
    createdAt: "2026-02-15",
  },
]
